### ISSUE TITLE
related to backup host and template .xml file in zabbix

### ISSUE THREAD

**Issue by giolong** [limosek/zaf#3]
Dear Lukas

i appreciate your code, and i think it very useful to me to

but when i use your code to back up template and host file in my zabbix server 

i was a trouble as below 

can you help me ? 

[root@zabbixtest ~]# zaf api export-templates zabbix-xml-templates/
zaf-error: Error processing API request. (1,/tmp//zapi16777)
zaf-error: Exiting with error!
EXPECTED value GOT EOF
zaf-warning: Will backup this templates:
zaf-warning: Output dir: zabbix-xml-templates/

i think problem occur with API 
my /etc/zaf.conf configuration 

ZAF_PKG='rpm'
ZAF_OS=''
ZAF_OS_CODENAME=''
ZAF_AGENT_PKG='zabbix-agent'
ZAF_GIT='0'
ZAF_CURL_INSECURE='0'
ZAF_TMP_DIR='/tmp/'
ZAF_CACHE_DIR='/tmp/zafc'
ZAF_LIB_DIR='/usr/lib/zaf'
ZAF_BIN_DIR='/usr/bin'
ZAF_PLUGINS_DIR='/usr/lib/zaf/plugins'
ZAF_REPO_URL='https://raw.githubusercontent.com/limosek/zaf-plugins/1.3/'
ZAF_PROXY=''
ZAF_REPO_DIR='/usr/lib/zaf/repo'
ZAF_AGENT_CONFIG='/etc/zabbix/zabbix_agentd.conf'
ZAF_AGENT_CONFIGD='/etc/zabbix/zabbix_agentd.d'
ZAF_AGENT_BIN='/usr/sbin/zabbix_agentd'
ZAF_FILES_UID='zabbix'
ZAF_FILES_GID='zabbix'
ZAF_FILES_UMASK='0770'
ZAF_AGENT_RESTART='service zabbix-agent restart'
ZAF_SERVER_CONFIG='/etc/zabbix/zabbix_server.conf'
ZAF_SERVER_CONFIGD='/etc/zabbix/zabbix_server.conf.d/'
ZAF_SERVER_EXTSCRIPTS='/usr/lib/zabbix/externalscripts'
ZAF_SERVER_BIN='/usr/sbin/zabbix_server'
ZAF_SUDOERSD='/etc/sudoers.d'
ZAF_CROND='/etc/cron.d'
ZAF_ZBXAPI_URL='http://neodalat.com/zabbix/api_jsonrpc.php'
ZAF_ZBXAPI_USER='zabbix'
ZAF_ZBXAPI_PASS='zabbix'
ZAF_ZBXAPI_AUTHTYPE='internal'
ZAF_AGENT_OPTIONS=' Z_Server=neodalat.com Z_ServerActive=neodalat.com'
ZAF_SERVER_OPTIONS=''

neodalat.com is my zabbix server

than you so much

**Comment by limosek** [comment]
Your zabbix API user must have superadmin permissions to work with templates.
Ufortunatelly it cannot easily detect if you have no permissions or it is another problem.
Closing now.
